language: go

# use containers which run faster and have cache
sudo: false

services:
  - docker

go:
  - 1.7.1
  - 1.7
  - 1.6

go_import_path: github.com/TuneLab/go-truss

# Attempt to build a truss-build image, run it to build docker image for
# building Truss, then run that image to actually build truss.
before_install:
  - make build-docker-build
  - make docker-build
  - ls -al build

# Use the output of the truss-build image run to build the truss runtime image.
install:
  - make build-docker-run

notifications:
  email: false
