language: go

# use containers which run faster and have cache
sudo: false

services:
  - docker

go:
  - 1.7.1
  - 1.7
  - 1.6

go_import_path: github.com/TuneLab/go-truss

# Attempt to build a truss-build image, run it to build docker
before_install:
  - make build-docker-build
  - make docker-build

install:
  - make build-docker-run

notifications:
  email: false
